version: '3.8'

services:
  churn_backend:
    image: zeeshanmurad65/churn_backend:v1
    container_name: churn_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  churn_frontend:
    image: zeeshanmurad65/churn_frontend:v1
    container_name: churn_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://churn_backend:8000
    depends_on:
      - churn_backend
    restart: unless-stopped